// These styles apply to every route in the application
import './globals.css';
import Header from './widgets/Header';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />
        {children}
        </body>
    </html>
  );
}